name: Release Test Report
run-name: Running a Release Test Report
on: [ pull_request, workflow_dispatch ]
permissions:
  contents: read
  actions: read
  checks: write
jobs:
  Run-Test:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 1.17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'zulu'
          cache: 'gradle'

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Run Debug Unit Tests
        run: ./gradlew test

      - name: Debug Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Debug JUnit Tests Result
          path: './app/build/test-results/testDebugUnitTest/TEST-*Test.xml'
          reporter: java-junit
          fail-on-error: true